version: '3'

services:
  test:
    container_name: cuda_server
    build: ./build
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./tansfer:/workspace
      - ./jupyter_server_config.json:/root/.jupyter/jupyter_server_config.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  cpu_test:
    container_name: cpu_server
    build: ./build
    ports:
      - "8882:8888"
      - "8002:8000"
    volumes:
      - ./tansfer:/workspace
