version: '3'

services:
  test:
    container_name: cuda_server
    image: nvidia/cuda:12.2.0-devel-ubuntu20.04
    build: ./build
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./tansfer:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  cpu_test:
    container_name: cpu_server
    image: nvidia/cuda:12.2.0-devel-ubuntu20.04
    build: ./build
    ports:
      - "8882:8888"
      - "8002:8000"
    volumes:
      - ./tansfer:/workspace
