version: '3'

services:
  test:
    container_name: cuda_server
    image: nvidia/cuda:12.2.0-devel-ubuntu20.04
    build: ./build
    ports:
        - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
